import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub,AiFillHtml5} from 'react-icons/ai'
import {FaCss3Alt, FaReact, FaPython , FaGithub, FaNodeJs} from 'react-icons/fa'
import { IoLogoJavascript } from "react-icons/io5"
import { SiArduino, SiMysql } from "react-icons/si";
import Image from 'next/image'
import nica from '../public/nica.JPG'
import simon from '../public/telasimon.png';
import credit from '../public/telacredit.png';
import movies from '../public/telamovies.png';
import React from 'react';
import { ContactUs } from '../src/components/Contact'; 
import { useState } from 'react';


export default function Home() {
const [darkMode, setDarkMode] = useState(false);



  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Marcelo Nicacio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' bg-gray-200 px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-20 flex justify-between'>
            <h1 className='text-xl font-burtons'>marcelo nicacio</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-gray-300 scale-x-[-1]'/>
              </li>
              <li><a className='typing bg-gradient-to-r from-blue-300 to-blue-400 text-black shadow-md px-4 py-2 rounded-md ml-8' href="#">Contact</a></li>
            </ul>
          </nav>
          
            <div className='flex flex-col justify-center items-center h-96'>
              <div>
                <h2 className='text-4xl md:text-6xl xl:text-7xl my-5 pt-10 dark:text-white'>Hi ,</h2>
                <h2 className='text-4xl md:text-6xl xl:text-7xl dark:text-white'> I'm <span className='bg-sky-400 shadow-lg text px-5 text-white dark:text-black'>MARCELO NICACIO</span></h2>
              </div>
              <h3 className='text:xl lg:text-2xl my-4 dark:text-white'>Developer Front-End</h3>
              <div className=' text-3xl flex justify-center gap-16 py-5 text-gray-600 dark:text-gray-400'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillGithub />
           
          </div>
            </div>
          
        </section>
        <section className='  grid grid-cols-1 lg:grid-cols-2 items-center' >
          <div className='max-w-lg py-5 my-20 mx-auto border-spacing-2  shadow-xl bg-blue-400 rounded-md flex flex-col items-center space-x-4'>
            <h3 className='text-3xl '>About me</h3>
            <p className='text-md py-2 dark:text-gray-200 leading-8 text-gray-800 md:text-xl mx-auto'>Developer Front-end based in Porto, Portugal and robotic lover.</p>
            <h4 className='text-4xl m-5' >Skills</h4>
            <div className=''>
              <ul className='text-6xl grid grid-cols-3 gap-6'>
                <li alt='HTML'><AiFillHtml5/></li>
                <li><FaCss3Alt/></li>
                <li><IoLogoJavascript/></li>
                <li><FaReact/></li>
                <li><FaNodeJs/></li>
                <li><FaPython/></li>
                <li><FaGithub/></li>
                <li><SiArduino/></li>
                <li><SiMysql/></li>
              </ul>
            </div>
          </div> 
         
            <div className='shadow-lg bg-green-300  max-w-lg mx-auto rounded-full overflow-hidden md:h-96 md:w-96'>
              <Image src={nica} alt={'foto marcelo'}/>
              </div>
          
  </section>
  <section className='min-h-screen'>

    <div ><h2 className='text-5xl my-10'>Projects</h2></div>

        <div className='grid-cols-1 grid md:grid-cols-2 md:gap-5 lg:grid-cols-3' >
            <div className='mb-20 flex flex-col justify-between text-start text-sm overflow-hidden max-w-xs h-96 bg-gray-400 shadow-lg  rounded-2xl dark:bg-white'>
              <div className='max-w-md'>
                <Image className='object-contain cursor-pointer' src={simon} alt={'imagem projeto simon'} />
              </div>
              <h3 className='text-lg font-medium p-2'>Simon Says!</h3>
              <p className='p-2 text-gray-700'>This project simula the classic toy Simon, the game have the same nostalgic colors and sounds. 
              </p>
              <h4 className='p-2 text-sky-700'>Technologies used...</h4>
              <div className='flex justify-around gap-1 items-center p-2' >
               <span className='bg-gray-500 text-xs rounded-xl px-2 text-white'>HTML</span><span className='bg-gray-500 text-xs rounded-xl px-2 text-white'>CSS</span><span className='bg-gray-500 text-xs rounded-xl px-2 text-white'>JavaScript</span>
               <span className='bg-gray-700 rounded-lg text-xs px-2 text-white cursor-pointer'>View More!</span>
              </div>
            
            </div>
            
            <div className='text-start mb-20 flex flex-col justify-between  text-sm overflow-hidden max-w-xs h-96  bg-gray-400 shadow-lg  rounded-2xl dark:bg-white'>
              <div className='max-w-xl  '>
                <Image className='object-contain w-96 cursor-pointer' src={credit} alt={'imagem projeto rocket card'} />
              </div>
              <h3 className='text-lg font-medium p-2'>Rocket Card</h3>
              <p className='p-2 text-gray-700'>Credit card project with Regular expression to identify the card company.</p>
              <h4 className='p-2 text-sky-700'>Technologies used...</h4>
              <div className='flex justify-around gap-1 items-center p-2' >
               <span className='bg-gray-500 text-xs rounded-xl px-2 text-white'>CSS</span><span className='bg-gray-500 text-xs rounded-xl px-2 text-white'>React JS</span><span className='bg-gray-500 text-xs rounded-xl px-2 text-white'>JavaScript</span>
               <span className='bg-gray-700 rounded-lg text-xs px-2 text-white cursor-pointer'>View More!</span>
              </div>
            
            </div>
            <div className='text-start mb-20 flex flex-col justify-between  h-96 text-sm max-w-xs overflow-hidden  bg-gray-400 shadow-lg rounded-2xl dark:bg-white'>
              <div className='max-w-xl  '>
                <Image className='object-contain cursor-pointer w-96' src={movies} alt={'imagem projeto movies'} />
              </div>
              <h3 className='text-lg font-medium p-2'>Best Movies IMDB</h3>
              <p className='p-2 text-gray-700'>This project show the best movies order list on Imdb and description about each movie.</p>
              <h4 className='p-2 text-sky-700'>Technologies used...</h4>
              <div className='flex justify-around gap-1 items-center p-2' >
               <span className='bg-gray-500 text-xs rounded-xl px-2 text-white'>React JS</span><span className='bg-gray-500 text-xs rounded-xl px-2 text-white'>CSS</span><span className='bg-gray-500 text-xs rounded-xl px-2 text-white'>JavaScript</span>
               <span className='bg-gray-700 rounded-lg text-xs px-2 text-white cursor-pointer'>View More!</span>
              </div>
            
            </div>
          </div>
        </section> 
        <section className='min-h-screen flex items-center justify-center bg-blue-400'>
          <ContactUs/>
        </section>
      </main>
      <footer className='flex justify-center items-center'><h4>Marcelo Nicacio - 2023</h4></footer>
    </div>
  )
}
